# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SensorService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SensorService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SensorService.proto\x12\x0biot_service\"\x07\n\x05\x45mpty\"\"\n\x0eStringResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t2Z\n\rSensorService\x12I\n\x14GetUltimaTemperatura\x12\x12.iot_service.Empty\x1a\x1b.iot_service.StringResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_STRINGRESPONSE']._serialized_start=45
  _globals['_STRINGRESPONSE']._serialized_end=79
  _globals['_SENSORSERVICE']._serialized_start=81
  _globals['_SENSORSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
